# Generated by Django 4.2.30 on 2026-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faculty_add_department'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='syllabus',
            name='unique_syllabus_per_dept_year_sem',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(default='', help_text='Department this faculty member belongs to.', max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='title',
            field=models.CharField(help_text='Short description, e.g. B.Tech CSE Semester III Syllabus', max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('department', 'academic_year', 'semester')},
        ),
    ]
