# Generated by Django 4.2.30 on 2026-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_user_semester_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistereduser',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='Programme span e.g. 2025-27 (set by student at registration)', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
